# Generated by Django 5.1.3 on 2024-11-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.IntegerField(unique=True)),
                ('Grid_ID', models.CharField(max_length=50, unique=True)),
                ('Grid_E_NAD83', models.IntegerField()),
                ('Grid_N_NAD83', models.IntegerField()),
                ('UTM_Zone', models.IntegerField()),
                ('Grid_Lat_NAD83', models.FloatField()),
                ('Grid_Long_NAD83', models.FloatField()),
                ('BCR', models.IntegerField()),
                ('MgmtEntity', models.CharField(max_length=200)),
                ('MgmtRegion', models.CharField(max_length=200)),
                ('MgmtUnit', models.CharField(max_length=200)),
                ('MgmtDistrict', models.CharField(max_length=200)),
                ('County', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=5)),
                ('PriorityLandscape', models.CharField(max_length=200)),
                ('inPL', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesID', models.IntegerField(unique=True)),
                ('species', models.CharField(max_length=200)),
                ('birdcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbci', models.FloatField()),
                ('posterior_median', models.FloatField()),
                ('ubci', models.FloatField()),
                ('gridID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.grid')),
                ('bird_speciesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.species')),
            ],
        ),
    ]
# Generated by Django 5.1.3 on 2024-11-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.IntegerField(unique=True)),
                ('Grid_ID', models.CharField(max_length=50, unique=True)),
                ('Grid_E_NAD83', models.IntegerField()),
                ('Grid_N_NAD83', models.IntegerField()),
                ('UTM_Zone', models.IntegerField()),
                ('Grid_Lat_NAD83', models.FloatField()),
                ('Grid_Long_NAD83', models.FloatField()),
                ('BCR', models.IntegerField()),
                ('MgmtEntity', models.CharField(max_length=200)),
                ('MgmtRegion', models.CharField(max_length=200)),
                ('MgmtUnit', models.CharField(max_length=200)),
                ('MgmtDistrict', models.CharField(max_length=200)),
                ('County', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=5)),
                ('PriorityLandscape', models.CharField(max_length=200)),
                ('inPL', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesID', models.IntegerField(unique=True)),
                ('species', models.CharField(max_length=200)),
                ('birdcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbci', models.FloatField()),
                ('posterior_median', models.FloatField()),
                ('ubci', models.FloatField()),
                ('gridID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.grid')),
                ('bird_speciesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.species')),
            ],
        ),
    ]
